---
title: "SCRI simulation - Results of simulations based on real-world data"
author: "Trang Tu"
format: docx
execute: 
  echo: false
  warning: false
  message: false
  output: true
  freeze: auto
editor: visual
---

```{r}
if (!require("pacman", quietly = TRUE)) {
  install.packages("pacman")
}
library(pacman)
pacman::p_load(knitr, 
               dplyr,
               readr,
               tidyr,
               here,
               rio
)
options(scipen = 999)
```

::: landscape

# 1. Base case without time-varying confounding 

```{r}
scens_real_base <- import(here("Results/Summary/Summary_real_test_20260412.xlsx"))

scens_real_base <- scens_real_base %>% 
  mutate(
    "Estimated VE (95% MC CI)" = paste0(round(VE_mean_est,3), " (", 
                                        round(VE_mean_est_low_CI,3), ",", 
                                        round(VE_mean_est_up_CI,3) ,")"),
    "Bias of est_V (MCSE)" = paste0(round(bias_est_V,3), " (", round(bias_est_V_MCSE,3), ")"),
  "Relative bias of est_V (MCSE)" = paste0(round(relative_bias_est_V,3), " (",
                                           round(relative_bias_est_V_MCSE,3), ")"),
  
  "Empirical SE of est_V (MCSE)" = paste0(round(se_est_V_hat,3), " (", 
                                          round(se_est_V_hat_MCSE,3), ")"),
  "Coverage of 95% CI of VE (MCSE)" = paste0(round(coverage_irr_V,3), " (",                                                                   round(coverage_irr_V_MCSE,3), ")"),
  Scenario = if_else(risk_end == 21, "Correct model specification",
                     "Misspecify end of risk window"),
      methods_fac = factor(methods, levels = c("no_calendar", "calendar_30d", "calendar_7d"),
                         label = c("No calendar adjustment", 
                                   "Calendar adjustment (30-day bin", 
                                   "Calendar adjustment (7-day bin"))
  )  %>% 
  rename("Cohort size" = cohort_size,
         "SCCS model" = methods_fac) %>%
  arrange(Scenario, "SCCS model", "Cohort size")
```


```{r}
#| label: tbl-basecase
#| tbl-cap: "Performance metrics for Base case"
#| tbl-colwidths: [15, 15, 14, 14, 14, 14, 14]

basecase_table <- scens_real_base %>%

 select(Scenario, "Cohort size", "SCCS model", 
        "Estimated VE (95% MC CI)", "Bias of est_V (MCSE)",  "Relative bias of est_V (MCSE)",
        "Coverage of 95% CI of VE (MCSE)")

kable(basecase_table)
```

# 2. Scenarios with time-varying confounding 

```{r}
scens_real <- import(here("Results/Summary/Summary_real_20260412.xlsx"))

scens_real <- scens_real %>% 
  mutate(
    "Estimated VE (95% MC CI)" = paste0(round(VE_mean_est,3), " (", 
                                        round(VE_mean_est_low_CI,3), ",", 
                                        round(VE_mean_est_up_CI,3) ,")"),
    "Bias of est_V (MCSE)" = paste0(round(bias_est_V,3), " (", round(bias_est_V_MCSE,3), ")"),
  "Relative bias of est_V (MCSE)" = paste0(round(relative_bias_est_V,3), " (",
                                           round(relative_bias_est_V_MCSE,3), ")"),
  
  "Empirical SE of est_V (MCSE)" = paste0(round(se_est_V_hat,3), " (", 
                                          round(se_est_V_hat_MCSE,3), ")"),
  "Coverage of 95% CI of VE (MCSE)" = paste0(round(coverage_irr_V,3), " (",                                                                   round(coverage_irr_V_MCSE,3), ")"),
  Scenario = if_else(risk_end == 21, "Correct model specification",
                     "Misspecify end of risk window"),
      methods_fac = factor(methods, levels = c("no_calendar", "calendar_30d", "calendar_7d"),
                         label = c("No calendar adjustment", 
                                   "Calendar adjustment (30-day bin", 
                                   "Calendar adjustment (7-day bin"))
  )  %>% 
  rename("Cohort size" = cohort_size,
         "SCCS model" = methods_fac) %>%
  arrange(Scenario, "SCCS model", "Cohort size")
```


```{r}
#| label: tbl-real_dat
#| tbl-cap: "Performance metrics for Scenarios with time-varying confounding"
#| tbl-colwidths: [15, 15, 14, 14, 14, 14, 14]

real_dat_table <- scens_real %>%

 select(Scenario, "Cohort size", "SCCS model", 
        "Estimated VE (95% MC CI)", "Bias of est_V (MCSE)",  "Relative bias of est_V (MCSE)",
        "Coverage of 95% CI of VE (MCSE)")

kable(real_dat_table)
```